# Exersices 1 ~ 10

- [exersice1](#anchor1)
        Import the numpy package under the name np (★☆☆)
- [exersice2](#anchor2)
        Print the numpy version and the configuration (★☆☆)
- [exersice3](#anchor3)
        Create a null vector of size 10 (★☆☆)
- [exersice4](#anchor4)
        How to find the memory size of any array (★☆☆)
- [exersice5](#anchor5)
        How to get the documentation of the numpy add function from the command line? (★☆☆)
- [exersice6](#anchor6)
        Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
- [exersice7](#anchor7)
        
- [exersice8](#anchor8)
- [exersice9](#anchor9)
- [exersice10](#anchor10)

<a id="anchor1"></a>
# <a href="#anchor1">exersice 1</a>

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

<a id="anchor2"></a>
# <a href="#anchor2">exersice 2</a>

2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.11.3


In [ ]:
np.show_config()

`np.show_config()`の見方は知らなかった。

<a id="anchor3"></a>
# <a href="#anchor3">exersice 3</a>

3. Create a null vector of size 10 (★☆☆)

In [9]:
a = np.zeros(10)
print(a)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


<a id="anchor4"></a>
# <a href="#anchor4">exersice 4</a>

4. How to find the memory size of any array (★☆☆)

In [11]:
a = np.zeros(10)
print(a.size * a.itemsize)

80


直接メモリを出力する関数はないのだろうか...

出し方は単純に**要素数**に**1要素あたりのメモリ**をかければよい

<a id="anchor5"></a>
# <a href="#anchor1">exersice 5</a>

5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


pythonコマンドで　`-c --cmd <string>`　のように引数を指定すれば文字列をプラグラムとして実行できる。

これは

```python
import numpy
numpy.info(numpy.add)
```

と同様である。

<a id="anchor6"></a>
# <a href="#anchor6">exersice 6</a>

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
a = np.zeros(10)
a[4] = 1
print(a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


<a id="anchor7"></a>
# <a href="#anchor7">exersice 7</a>

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
a = np.arange(0, 50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


<a id="anchor8"></a>
# <a href="#anchor8">exersice 8</a>

8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
a = np.arange(0, 10)
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


スライスでは上記のように、 `-1` を指定すれば逆順でアクセスできる。

<a id="anchor9"></a>
# <a href="#anchor9">exersice 9</a>

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
a = np.arange(0, 9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<a id="anchor10"></a>
# <a href="#anchor10">exersice 10</a>

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [44]:
# このやり方だと0でない要素を抽出する
a = np.array([1, 2, 0, 0, 4, 0])
print(a[a != 0])

# 以下のように0からはじまるインデックスを作成してアクセスする
b = np.arange(a.size).reshape(a.shape)
print(b[a != 0])

[1 2 4]
[0 1 4]


### 解答：専用の関数があるらしい。

In [31]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [32]:
??np.nonzero

### 2次元データで確認する

In [47]:
# 取得できる整数値は [low, high) 
a = np.random.randint(low=0, high=2, size=(3,3))
print(a)

[[1 1 1]
 [0 0 0]
 [0 1 1]]


In [48]:
np.nonzero(a)

(array([0, 0, 0, 2, 2], dtype=int64), array([0, 1, 2, 1, 2], dtype=int64))

In [49]:
idx = np.arange(a.size).reshape(a.shape)
print(idx)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [50]:
print(idx[a != 0])

[0 1 2 7 8]


上記の2例から、 `np.nonzero` 関数は、次元数に従う数の配列を返すことがわかる