- [exersice11](#anchor11) : OK
        Create a 3x3 identity matrix (★☆☆)
- [exersice12](#anchor12) : OK
        Create a 3x3x3 array with random values (★☆☆)
- [exersice13](#anchor13) : OK
        Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
- [exersice14](#anchor14) : OK
        Create a 2d array with 1 on the border and 0 inside (★☆☆)
- [exersice15](#anchor15) : OK
        Create a 2d array with 1 on the border and 0 inside (★☆☆)
- [exersice16](#anchor16) : check
        How to add a border (filled with 0's) around an existing array? (★☆☆)
- [exersice17](#anchor17) : check
        What is the result of the following expression? (★☆☆)
- [exersice18](#anchor18) : No
        Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
- [exersice19](#anchor19) : No
        Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
- [exersice20](#anchor20) : No
        Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [2]:
import numpy as np

<a id="anchor11"></a>
# <a href="#anchor11">exersice 11</a>

11. Create a 3x3 identity matrix (★☆☆)

In [3]:
a = np.eye(3)
print(a)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


<a id="anchor12"></a>
# <a href="#anchor12">exersice 12</a>

12. Create a 3x3x3 array with random values (★☆☆)

In [4]:
a = np.random.rand(3, 3, 3)
print(a)

[[[ 0.11554532  0.68612736  0.07472155]
  [ 0.50568244  0.60005432  0.85647485]
  [ 0.58793887  0.46553517  0.97024689]]

 [[ 0.84230877  0.99788781  0.34345734]
  [ 0.09379807  0.68850787  0.2188372 ]
  [ 0.69588256  0.34469699  0.64932022]]

 [[ 0.53008486  0.50689337  0.10096036]
  [ 0.04992829  0.88789691  0.88047927]
  [ 0.20822965  0.98747172  0.77993748]]]


### 模範

In [5]:
a = np.random.random((3,3,3))
print(a)

[[[ 0.32933931  0.51394256  0.97366296]
  [ 0.72189293  0.82275697  0.29840614]
  [ 0.23078927  0.8996423   0.71399358]]

 [[ 0.25392097  0.34276567  0.73202868]
  [ 0.68628416  0.83064406  0.07378882]
  [ 0.78397156  0.43012539  0.45870149]]

 [[ 0.50570435  0.09706386  0.942148  ]
  [ 0.51273464  0.46336409  0.23015645]
  [ 0.73210504  0.50432055  0.96138379]]]


<a id="anchor13"></a>
# <a href="#anchor13">exersice 13</a>

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random((10, 10))
print(a)

[[ 0.02584145  0.91115304  0.35112219  0.24626549  0.20899342  0.02350835
   0.12177419  0.06845239  0.83962482  0.26865076]
 [ 0.78642978  0.91990847  0.80558152  0.08782037  0.28367789  0.79786722
   0.48851796  0.99962946  0.12272645  0.97231384]
 [ 0.25290104  0.59112104  0.12722352  0.96661385  0.51938929  0.58529302
   0.10496069  0.65630398  0.60196498  0.75160905]
 [ 0.60431448  0.14201503  0.07149635  0.36168062  0.74941922  0.9252933
   0.47999238  0.8213849   0.99251414  0.22781972]
 [ 0.51074653  0.7107853   0.67127887  0.01682334  0.93519461  0.20498849
   0.48601419  0.82814581  0.62608219  0.26890882]
 [ 0.13877276  0.19346699  0.38514952  0.80129502  0.94517442  0.85765665
   0.33800048  0.45994799  0.7091633   0.39288109]
 [ 0.72557582  0.89962964  0.17109248  0.2996356   0.27009509  0.13761503
   0.47907507  0.08739207  0.51676538  0.56383808]
 [ 0.13930355  0.46395563  0.15529448  0.77403328  0.93993861  0.45560535
   0.31124269  0.92264591  0.68579973  0.40080526]
 

In [17]:
print('a shape : {}'.format(a.shape))

a shape : (10, 10)


In [19]:
print('a maximum : {}'.format(a.max()))
print('a manimum : {}'.format(a.min()))

a maximum : 0.9996294576921902
a manimum : 0.01682334042458189


### 模範

In [20]:
a = np.random.random((10, 10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.00436688653178 0.980412407877


タプル形式で渡す方法は便利なので、頭に入れておく。

<a id="anchor14"></a>
# <a href="#anchor14">exersice 14</a>

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
a = np.random.random(30)
amean = a.mean()
print(amean)

0.492192823821


<a id="anchor15"></a>
# <a href="#anchor15">exersice 15</a>

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [31]:
a = np.ones((4, 4))
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [32]:
a[1:3, 1:3] = 0
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  1.  1.  1.]]


### 模範

In [28]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


#### ポイント

スライスで指定する際に、1つだけ内部を指定して、その配列をスライスに渡せばよい

<a id="anchor16"></a>
# <a href="#anchor16">exersice 16</a>

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [33]:
a = np.random.random((3, 3))
print(a)

[[ 0.22186722  0.90782891  0.92126089]
 [ 0.16827014  0.134656    0.59736803]
 [ 0.93705023  0.94527088  0.08356986]]


In [36]:
b = np.zeros((a.shape[0]+2, a.shape[1]+2))
b[1:-1, 1:-1] = a
print(b)

[[ 0.          0.          0.          0.          0.        ]
 [ 0.          0.22186722  0.90782891  0.92126089  0.        ]
 [ 0.          0.16827014  0.134656    0.59736803  0.        ]
 [ 0.          0.93705023  0.94527088  0.08356986  0.        ]
 [ 0.          0.          0.          0.          0.        ]]


形状を間違えないようにする。

上下左右に要素を追加するので、元の大きさから、行も列も2つ分大きくなる。

### 模範

In [37]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [38]:
!python -c "import numpy; numpy.info(numpy.pad)"

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

`pad` 関数を使用することで、渡した配列に任意の `padding` ができる。

引数は下記の3つ
- pad_width : 追加するpaddingの幅
- mode : 定数や最大値、線形補間など様々
- constant_values (as **kwargs) : modeで指定した値

<a id="anchor17"></a>
# <a href="#anchor17">exersice 17</a>

17. What is the result of the following expression? (★☆☆)

In [39]:
print(0 * np.nan)

nan


`np.nan` とはNumpy形式のNANであり、これにどんな数値を計算しても、帰ってくる値はNANとなる？

In [40]:
print(np.nan == np.nan)

False


In [41]:
print(np.inf > np.nan)

False


In [42]:
print(np.nan - np.nan)

nan


In [43]:
print(0.3 == 3 * 0.1)

False


`map` 関数で `id` を割り当ててみるとこれは理解しやすい（[参考](https://stackoverflow.com/questions/20320022/why-in-numpy-nan-nan-is-false-while-nan-in-nan-is-true)）。

In [48]:
nans = [np.nan for i in range(2)]
list(map(id, nans))

[1185528658896, 1185528658896]

In [49]:
nans = [float("nan") for i in range(2)]
list(map(id, nans))

[1185542614040, 1185542614088]

In [50]:
vars = [0.3, 3*0.1]
list(map(id, vars))

[1185542614136, 1185542614304]

あくまで数値が同じということではなく、割り当てられたポインタが同じかどうかを見ています。

<a id="anchor18"></a>
# <a href="#anchor18">exersice 18</a>

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [53]:
a = np.diag([0, 1, 2, 3, 4])
print(a)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


問題の意味を取り違えていた...

対角線のすぐ下の値を `[1, 2, 3, 4]` にせよ。という意味

### 模範

In [54]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


引数 `k` で対角線を入れる場所を指定できる？

<a id="anchor19"></a>
# <a href="#anchor19">exersice 19</a>

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

ブロック状の白黒模様みたいなもの

|黒|白|黒|白|黒|
|:-:|:-:|:-:|:-:|:-:|
|白|黒|白|黒|白|
|黒|白|黒|白|黒|
|白|黒|白|黒|白|
|黒|白|黒|白|黒|

In [67]:
a = np.array([0, 1]*32).reshape((8, 8))
print(a)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


### 模範

In [69]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


<a id="anchor20"></a>
# <a href="#anchor20">exersice 20</a>

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [77]:
a = np.random.rand(6, 7, 8)
print(a.shape)

(6, 7, 8)


数値的に考えた場合。

1行の中に、`7*8 = 56` 要素が存在いると考えられる。

そのため、100番目の要素とは、2行目(57 ~ )の、

6列目(`56 + (7 * 6 = 42) == 96 ~ `)の、

4番目の要素(`96 + 4 == 100`)である。

Python記法では0から数え上げるため、(1, 5, 3)となることが予想できる。

In [73]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [76]:
!python -c "import numpy; numpy.info(numpy.unravel_index)"

unravel_index(indices, dims, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``dims``. Before version 1.6.0,
    this function accepted just one index value.
dims : tuple of ints
    The shape of the array to use for unraveling ``indices``.
order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 13], (7,6), order='F')
(array([3, 6, 6]), array([4, 5, 1]))

>>> np.unravel_index