- [exersice21](#anchor21) : check
        Create a checkerboard 8x8 matrix using the tile function (★☆☆)
- [exersice22](#anchor22) : OK
        Normalize a 5x5 random matrix (★☆☆)
- [exersice23](#anchor23) : check
        Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
- [exersice24](#anchor24) : OK
        Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
- [exersice25](#anchor25) : check
        Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
- [exersice26](#anchor26) : check
        What is the output of the following script? (★☆☆)
- [exersice27](#anchor27) : check
        Consider an integer vector Z, which of these expressions are legal? (★☆☆)
- [exersice28](#anchor28) : check
         What are the result of the following expressions?
- [exersice29](#anchor29) : check
        How to round away from zero a float array ? (★☆☆)
- [exersice30](#anchor30) : check
        How to find common values between two arrays? (★☆☆)

In [1]:
import numpy as np

<a id="anchor21"></a>
# <a href="#anchor21">exersice 21</a>

21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [2]:
"""
np.tile(A, reps) returns an array of A * reps

np.tile([0, 1, 2], reps=3)
>> [0,1,2, 0,1,2, 0,1,2]
"""

a = np.tile([[1, 0], [0, 1]], reps=4)
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [3]:
a = np.array([a, a, a, a])
print(a.shape)

(4, 2, 8)


### 模範

In [4]:
Z = np.tile(np.array([[0, 1], [1, 0]]), reps=(4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


repsに整数だけではなく、配列も指定できることに注意。

公式ドキュメントの、引数の定義を要参照

In [5]:
!python -c "import numpy; numpy.info(numpy.tile)"

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

<a id="anchor22"></a>
# <a href="#anchor22">exersice 22</a>

22. Normalize a 5x5 random matrix (★☆☆)

※ 値を `[0, 1]` の範囲内にまとめる

In [6]:
a = np.random.random((5, 5))
amin, amax = a.min(), a.max()
a = (a - amin) / (amax - amin)
print(a)

[[ 0.78361138  0.5120811   0.71621848  0.82807249  1.        ]
 [ 0.19457924  0.09505236  0.25335177  0.18652206  0.85315084]
 [ 0.1575176   0.62689327  0.0497441   0.28506825  0.77326032]
 [ 0.17616359  0.26178485  0.          0.98647066  0.07975579]
 [ 0.68952388  0.85907683  0.65664589  0.599395    0.5014065 ]]


<a id="anchor23"></a>
# <a href="#anchor23">exersice 23</a>

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

- `dtype`を指定して配列生成
- 変化しない4バイト（`[Red, Green, Blue, Alpha]`）

In [7]:
a = np.array([255, 255, 255, 0.5], dtype=np.uint8)
print(a)

[255 255 255   0]


### 模範

In [8]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [9]:
!python -c "import numpy; numpy.info(numpy.dtype)"

 dtype()

dtype(obj, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
obj
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', '<i2

Numpyでは、 `uint8` と `ubyte` は同じ

In [10]:
!python -c "import numpy; numpy.info(numpy.ubyte)"

 uint8()

Base class for numpy scalar types.

Class from which most (all?) numpy scalar types are derived.  For
consistency, exposes the same API as `ndarray`, despite many
consequent attributes being either "get-only," or completely irrelevant.
This is the class from which it is strongly suggested users should derive
custom scalar types.


Methods:

  all  --  Not implemented (virtual attribute)
  any  --  Not implemented (virtual attribute)
  argmax  --  Not implemented (virtual attribute)
  argmin  --  Not implemented (virtual attribute)
  argsort  --  Not implemented (virtual attribute)
  astype  --  Not implemented (virtual attribute)
  byteswap  --  Not implemented (virtual attribute)
  choose  --  Not implemented (virtual attribute)
  clip  --  Not implemented (virtual attribute)
  compress  --  Not implemented (virtual attribute)
  conj  --  None
  conjugate  --  Not implemented (virtual attribute)
  copy  --  Not implemented (virtual attribute)
  cumprod  --  Not implemented (

<a id="anchor24"></a>
# <a href="#anchor24">exersice 24</a>

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
a = np.ones((5, 3))
print(a.shape)
b = np.random.rand(3, 2)
print(b.shape)

(5, 3)
(3, 2)


In [12]:
ab = np.dot(a, b)
print(ab.shape)
print(ab)

(5, 2)
[[ 1.91258123  1.37311343]
 [ 1.91258123  1.37311343]
 [ 1.91258123  1.37311343]
 [ 1.91258123  1.37311343]
 [ 1.91258123  1.37311343]]


### 別解

Python 3.5 以上のバージョンで以下のような記法が導入されたらしい。

In [13]:
ab = np.ones((5, 3)) @ np.random.rand(3, 2)
print(ab.shape)
print(ab)

(5, 2)
[[ 1.68927779  1.31379757]
 [ 1.68927779  1.31379757]
 [ 1.68927779  1.31379757]
 [ 1.68927779  1.31379757]
 [ 1.68927779  1.31379757]]


<a id="anchor25"></a>
# <a href="#anchor25">exersice 25</a>

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

要は符号を反転させてくださいという意味です。

In [14]:
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [15]:
a[(a >= 3) & (a <= 8)] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


<a id="anchor26"></a>
# <a href="#anchor26">exersice 26</a>

26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [16]:
print(sum(range(5), -1))

9


In [17]:
from numpy import *

print(sum(range(5), -1))

10


In [18]:
a = np.arange(10).reshape((2, 5))
print(a)
print(sum(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
45


In [19]:
print(sum(a, -1))

[10 35]


**組み込み関数sum()**

組み込み関数の `sum()` では2番目の引数にどこから数え上げるのかを指定できます。

[公式ドキュメント](https://docs.python.jp/3/library/functions.html#sum)を参照

**numpy.sum()**

`-1` を指定することで最大次元数方向での演算を行います。

この場合は2次元行列なので、列方向の和を計算しています。

<a id="anchor27"></a>
# <a href="#anchor27">exersice 27</a>

27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 要素ごとの累乗を行う。
a ** a

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489], dtype=int32)

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# << や >> はビットシフトの演算子
# x = x * 2^a or x = x / 2^a を行う
2 << a

array([   4,    8,   16,   32,   64,  128,  256,  512, 1024], dtype=int32)

In [22]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a << 2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36], dtype=int32)

In [23]:
2 << a >> 2

array([  1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [24]:
a <- a # this is the same exsample of a < (-a)

array([False, False, False, False, False, False, False, False, False], dtype=bool)

In [25]:
1j * a # 1j replesent complex part

array([ 0.+1.j,  0.+2.j,  0.+3.j,  0.+4.j,  0.+5.j,  0.+6.j,  0.+7.j,
        0.+8.j,  0.+9.j])

In [26]:
a/1/1 # change integer type to float type (by division)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [27]:
a < a > a

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

<a id="anchor28"></a>
# <a href="#anchor28">exersice 28</a>

28. What are the result of the following expressions?

```python
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
```

In [28]:
a = np.array(0)
print(a)
print(type(a))

0
<class 'numpy.ndarray'>


In [29]:
print(np.array(0) / np.array(0))

nan


C:\Users\s-k85\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [30]:
print(np.array(0) // np.array(0))

0


C:\Users\s-k85\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [31]:
a = np.array(np.nan)
print(a)
print(type(a))

nan
<class 'numpy.ndarray'>


In [32]:
print(a.astype('int'))

-2147483648


In [33]:
print(np.array([np.nan]).astype(int).astype(float))

[ -2.14748365e+09]


<a id="anchor29"></a>
# <a href="#anchor29">exersice 29</a>

29. How to round away from zero a float array ? (★☆☆)

In [34]:
a = np.random.uniform(low=-10, high=10, size=10)
print(a)

[ 8.13792987  9.18346068  1.66228975  6.40071079  0.23687039 -0.81206184
  9.27714033  0.79803461 -0.78602341 -9.43304721]


In [35]:
np.round(a)

array([ 8.,  9.,  2.,  6.,  0., -1.,  9.,  1., -1., -9.])

`round`関数はあくまで四捨五入なので、0の方向へ丸め込む必要がある？

In [36]:
np.ceil(a)

array([  9.,  10.,   2.,   7.,   1.,  -0.,  10.,   1.,  -0.,  -9.])

`ceil`関数は、正の無限大方向への丸め込みです。

In [37]:
# Author: Charles R Harris
print(np.copysign(np.ceil(np.abs(a)), a))

[  9.  10.   2.   7.   1.  -1.  10.   1.  -1. -10.]


答えが間違っているのか、問題のとらえ方が間違っている。

<a id="anchor30"></a>
# <a href="#anchor30">exersice 30</a>

30. How to find common values between two arrays? (★☆☆)

In [38]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([5,6,7,8,9,10,11])

In [39]:
np.intersect1d(a, b)

array([5, 6, 7, 8])

In [40]:
!python -c "import numpy; numpy.info(numpy.intersect1d)"

 intersect1d(ar1, ar2, assume_unique=False)

Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.

Parameters
----------
ar1, ar2 : array_like
    Input arrays.
assume_unique : bool
    If True, the input arrays are both assumed to be unique, which
    can speed up the calculation.  Default is False.

Returns
-------
intersect1d : ndarray
    Sorted 1D array of common and unique elements.

See Also
--------
numpy.lib.arraysetops : Module with a number of other functions for
                        performing set operations on arrays.

Examples
--------
>>> np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
array([1, 3])

To intersect more than two arrays, use functools.reduce:

>>> from functools import reduce
>>> reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
array([3])
