- [exersice31](#anchor31) : check
    - How to ignore all numpy warnings (not recommended)? (★☆☆)
- [exersice32](#anchor32) : check
    - Is the following expressions true? (★☆☆)
- [exersice33](#anchor33) : check
    - How to get the dates of yesterday, today and tomorrow? (★☆☆)
- [exersice34](#anchor34) : check
    - How to get all the dates corresponding to the month of July 2016? (★★☆)
- [exersice35](#anchor35) : check
    - How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
- [exersice36](#anchor36) : check
    - Extract the integer part of a random array using 5 different methods (★★☆)
- [exersice37](#anchor37) : check
    - Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
- [exersice38](#anchor38) : check
    - Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
- [exersice39](#anchor39) : check
    - Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
- [exersice40](#anchor40) : check
    - Create a random vector of size 10 and sort it (★★☆)

In [2]:
import numpy as np

<a id="anchor31"></a>
# <a href="#anchor31">exersice 31</a>

31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [6]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

<a id="anchor32"></a>
# <a href="#anchor32">exersice 32</a>

32. Is the following expressions true? (★☆☆)

In [7]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\s-k85\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [10]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


C:\Users\s-k85\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


<a id="anchor33"></a>
# <a href="#anchor33">exersice 33</a>

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [13]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2018-08-08')

In [14]:
today = np.datetime64('today', 'D')
today

numpy.datetime64('2018-08-09')

In [15]:
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
tomorrow

numpy.datetime64('2018-08-10')

<a id="anchor34"></a>
# <a href="#anchor34">exersice 34</a>

34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [16]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

[公式ドキュメント](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html)

<a id="anchor35"></a>
# <a href="#anchor35">exersice 35</a>

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [17]:
a = np.ones((3, 3))
b = np.ones((3, 3))

In [24]:
print(a + b)

[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


In [23]:
print(-a / 2)

[[-0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5]]


In [22]:
c = (a + b) * (-a / 2)
print(c)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


### 模範

In [25]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

Numpyの四則演算関数(`np.add`, `np.divide`, `np.negative`, `np.multiply` など)は引数の `out=` に変数を解くことで出力をその変数に返すことができます。

<a id="anchor36"></a>
# <a href="#anchor36">exersice 36</a>

36. Extract the integer part of a random array using 5 different methods (★★☆)

In [29]:
a = np.random.randn(5, 5) * 2
print(a)

[[ 1.37865947  0.10896215 -1.8808759  -1.91074463 -0.41632885]
 [-0.96448531  4.94724541  0.98590099  1.20092437  0.03664011]
 [ 0.40811929 -2.37734129  0.60028029 -2.73937884  0.30584796]
 [-4.90284619 -1.9383866  -0.06989672  6.61909718  0.39220156]
 [-1.98028307  0.23834574 -2.39348892  0.52230242  2.93211953]]


##### 解1

In [32]:
print(np.array(a, dtype=int))

[[ 1  0 -1 -1  0]
 [ 0  4  0  1  0]
 [ 0 -2  0 -2  0]
 [-4 -1  0  6  0]
 [-1  0 -2  0  2]]


##### 解2

In [35]:
print(a.astype('int'))

[[ 1  0 -1 -1  0]
 [ 0  4  0  1  0]
 [ 0 -2  0 -2  0]
 [-4 -1  0  6  0]
 [-1  0 -2  0  2]]


##### 別解1

In [40]:
np.trunc(a)

array([[ 1.,  0., -1., -1., -0.],
       [-0.,  4.,  0.,  1.,  0.],
       [ 0., -2.,  0., -2.,  0.],
       [-4., -1., -0.,  6.,  0.],
       [-1.,  0., -2.,  0.,  2.]])

<a id="anchor37"></a>
# <a href="#anchor37">exersice 37</a>

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [47]:
a = np.array([0, 1, 2, 3, 4]*5).reshape((5, 5))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 別解

In [48]:
b = np.zeros((5,5))
b += np.arange(5)
print(b)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


これはNumpyの**ブロードキャスト**という演算を利用している。

5行5列の行列に、行ベクトルを足せば、全行にこのベクトルが加算される。

<a id="anchor38"></a>
# <a href="#anchor38">exersice 38</a>

38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

##### 模範

generatorに関してはほぼ無知なので調べる必要があり。

In [75]:
def generate():
    for x in range(10):
        yield x
b = np.fromiter(generate(),dtype=float,count=-1)
print(b)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


- `fromiter(iterable, dtype, count=-1)`

引数に**イテレータ**をとり、`dtype`に従って値をとり、配列を返す

<a id="anchor39"></a>
# <a href="#anchor39">exersice 39</a>

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [61]:
a = np.random.rand(10)
print(a)

[ 0.30804912  0.23603981  0.9579054   0.75118764  0.7203701   0.09125374
  0.90367871  0.98092891  0.02830191  0.35878824]


ただ単に0～1の乱数を生成した場合は、0や1を含んでいる場合が存在する。

In [69]:
np.random.seed(0)
b = np.random.rand(100000)
print(b.min(), b.max())

3.31055445735e-06 0.999977951781


##### 別解1

In [74]:
c = np.linspace(start=0,stop=1,num=11,endpoint=False)[1:]
print(c)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


この方法は、`start`から`stop`までを`num`等分を行い、その際に`stop`の点を含めないように`endpoint`で指定している。

このままでは、0は出力されてしまうので、インデックスが2番目の場所から抽出している。

<a id="anchor40"></a>
# <a href="#anchor40">exersice 40</a>

40. Create a random vector of size 10 and sort it (★★☆)

In [56]:
a = np.random.randint(10, size=20)
print(a)

[9 3 0 1 4 5 3 7 8 8 3 1 2 9 3 0 4 0 0 2]


##### 解1

In [57]:
np.sort(a)

array([0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 5, 7, 8, 8, 9, 9])

##### 解2

In [60]:
a.sort()
print(a)

[0 0 0 0 1 1 2 2 3 3 3 3 4 4 5 7 8 8 9 9]


この方法はもともとの配列を変えてしまうので使用するときは注意が必要